# Generated by Django 5.2.4 on 2025-08-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_vendorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='phone',
            new_name='business_phone',
        ),
    ]
