# Generated by Django 5.2.4 on 2025-08-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_phone_vendorprofile_business_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
