# Generated by Django 5.2.4 on 2025-08-24 16:04

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_vendorprofile_business_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=backend.utils.HashedUploadPath('users/profile_pictures'), validators=[backend.utils.validate_image_extension, backend.utils.validate_image_size]),
        ),
    ]
