# Generated by Django 5.2.4 on 2025-08-14 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='If True and active, show on frontend.')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent: use 10 for 10%. Fixed: currency units.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Global cap across all orders. Null = unlimited.', null=True)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Apply only if order subtotal >= this amount.', max_digits=10, null=True)),
                ('first_order_only', models.BooleanField(default=False, help_text="Use for the one-time welcome coupon (only valid on a user's first order).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'is_public', 'valid_from', 'valid_to'], name='orders_coup_is_acti_50af08_idx'), models.Index(fields=['code'], name='orders_coup_code_ca5871_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'fixed'), ('value__gte', 0)), models.Q(('discount_type', 'percent'), ('value__gte', 0), ('value__lte', 100)), _connector='OR'), name='coupon_value_range_by_type')],
            },
        ),
    ]
