# Generated by Django 5.2.4 on 2025-08-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
