# Generated by Django 5.2.4 on 2025-08-01 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_image_productimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank for top-level categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category'),
        ),
    ]
