# Generated by Django 5.2.4 on 2025-08-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_weekly_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='weekly_deal_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
