# Generated by Django 5.2.4 on 2025-08-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_is_weekly_deal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_weekly_deal',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='weekly_deal_expires',
        ),
        migrations.AddField(
            model_name='product',
            name='is_weekly_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='weekly_deal_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
