# Generated by Django 5.2.4 on 2025-08-10 21:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='productreview',
            name='unique_review_per_user_product',
        ),
        migrations.RemoveConstraint(
            model_name='productreview',
            name='rating_range',
        ),
        migrations.AddField(
            model_name='productreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products.productreview'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', '-created_at', '-id'], name='products_pr_product_e1b46c_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['parent', 'created_at', 'id'], name='products_pr_parent__a1e82e_idx'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('user', 'product'), name='unique_review_per_user_product'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='rating_range'),
        ),
    ]
