# Generated by Django 5.2.4 on 2025-08-24 16:04

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(upload_to=backend.utils.HashedUploadPath('products/'), validators=[backend.utils.validate_image_extension, backend.utils.validate_image_size]),
        ),
    ]
