# Generated by Django 5.2.4 on 2025-08-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_brand_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='vendor',
        ),
    ]
